version: '3.8'
services:
  php-fpm:
    container_name: homebrewing-storage-php
    build:
      context: ./docker/php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    links:
      - database
    restart: unless-stopped

  database:
    container_name: homebrewing-storage-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

  web:
    container_name: homebrewing-storage-web
    image: nginx:alpine
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
      - database
      - php-fpm
    restart: unless-stopped
